import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Posts from "../components/Posts";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Carhat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero />

      <Posts />
    </div>
  );
}
